# Generated by Django 3.0.2 on 2020-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='About_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Class',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
