# Generated by Django 3.0.2 on 2020-08-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200804_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
