# Generated by Django 3.0.2 on 2020-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_profile_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='school_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='schoolName',
        ),
        migrations.AddField(
            model_name='profile',
            name='school_contact_person',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
