# Generated by Django 3.0.2 on 2020-08-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Name', models.CharField(blank=True, max_length=80, null=True)),
                ('Class_section', models.CharField(blank=True, max_length=30, null=True)),
                ('Clas_Teacher', models.CharField(blank=True, max_length=80, null=True)),
                ('Class_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
