# Generated by Django 3.0.2 on 2020-08-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='Clas_Teacher',
            new_name='Clas_teacher',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='Class_Name',
            new_name='Class_name',
        ),
    ]
