# Generated by Django 3.0.2 on 2020-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20200806_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='Class_name',
        ),
        migrations.AddField(
            model_name='class',
            name='Class_Name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
