# Generated by Django 3.0.2 on 2020-08-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20200806_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='Clas_teacher',
            new_name='Class_teacher',
        ),
    ]
