# Generated by Django 3.0.2 on 2020-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20200806_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=80, null=True)),
                ('student_class', models.CharField(blank=True, max_length=80, null=True)),
                ('student_section', models.CharField(blank=True, max_length=80, null=True)),
                ('student_email', models.CharField(blank=True, max_length=80, null=True)),
                ('student_mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
